In [1]:
def getMin(nums):
    left, right = 0, len(nums)-1
    indexMid = left
    while nums[left] >= nums[right]:
        if right - left == 1:
            indexMid = right
            break
        indexMid = (left + right) >> 1
        if nums[indexMid] == nums[left] and nums[indexMid] == nums[right]:
            print(left, right, nums[left:right+1])
            return min(nums[left:right+1])
        if nums[indexMid] >= nums[left]:
            left = indexMid
        elif nums[indexMid] <= nums[right]:
            right = indexMid
    return nums[indexMid]

nums = [3,3,3,3,32,1,1,1,2,2,2,2,2,2,2,2]
getMin(nums)

In [2]:
def _printOneToN(nums, length, index):
    if index == length:
        print(nums,end=' ')
    else:
        for i in range(10):
            nums[index] = i
            _printOneToN(nums, length, index+1)

def PrintOneToN(length):
    nums = [0] * length
    _printOneToN(nums, length, 0)

PrintOneToN(2)

[0, 0] [0, 1] [0, 2] [0, 3] [0, 4] [0, 5] [0, 6] [0, 7] [0, 8] [0, 9] [1, 0] [1, 1] [1, 2] [1, 3] [1, 4] [1, 5] [1, 6] [1, 7] [1, 8] [1, 9] [2, 0] [2, 1] [2, 2] [2, 3] [2, 4] [2, 5] [2, 6] [2, 7] [2, 8] [2, 9] [3, 0] [3, 1] [3, 2] [3, 3] [3, 4] [3, 5] [3, 6] [3, 7] [3, 8] [3, 9] [4, 0] [4, 1] [4, 2] [4, 3] [4, 4] [4, 5] [4, 6] [4, 7] [4, 8] [4, 9] [5, 0] [5, 1] [5, 2] [5, 3] [5, 4] [5, 5] [5, 6] [5, 7] [5, 8] [5, 9] [6, 0] [6, 1] [6, 2] [6, 3] [6, 4] [6, 5] [6, 6] [6, 7] [6, 8] [6, 9] [7, 0] [7, 1] [7, 2] [7, 3] [7, 4] [7, 5] [7, 6] [7, 7] [7, 8] [7, 9] [8, 0] [8, 1] [8, 2] [8, 3] [8, 4] [8, 5] [8, 6] [8, 7] [8, 8] [8, 9] [9, 0] [9, 1] [9, 2] [9, 3] [9, 4] [9, 5] [9, 6] [9, 7] [9, 8] [9, 9] 

In [3]:
def ReorderOddEven(nums):
    if nums is None or nums == 0:
        return
    i, j = 0, len(nums)-1
    while i < j:
        while i < j and nums[i] & 1 != 0 :
            i += 1
        while i < j and nums[j] & 1 == 0:
            j -= 1
        if i < j:
            nums[i], nums[j] = nums[j], nums[i]

nums = [1,3,5,3,7,46,3,10,52,34,2,62,54,2,6,8,9,4,3]
ReorderOddEven(nums)
print(nums)

[1, 3, 5, 3, 7, 3, 3, 9, 52, 34, 2, 62, 54, 2, 6, 8, 10, 4, 46]


In [4]:
def findDuplicates(nums):
    L = len(nums)
    ret = []
    for i in range(L):
        if nums[i] is None:
            continue
        pos = nums[i] - 1
        while pos != i:
            if nums[i] and nums[pos]:
                print("nums[i]=%d, nums[pos]=%d "%(nums[i], nums[pos]),end=' ')
            if nums[pos] != nums[i]:
                nums[pos], nums[i] = nums[i], nums[pos]
                print("swap")
                if nums[i] is None: 
                    break
                pos = nums[i] - 1
            else:
                ret.append(nums[i])
                nums[i] = None
                break
    return sorted(ret)

nums=[4,3,2,7,8,2,3,1]
findDuplicates(nums)

nums[i]=4, nums[pos]=7  swap
nums[i]=7, nums[pos]=3  swap
nums[i]=3, nums[pos]=2  swap
nums[i]=2, nums[pos]=3  swap
nums[i]=3, nums[pos]=3  nums[i]=8, nums[pos]=1  swap
swap
nums[i]=2, nums[pos]=2  

[2, 3]

In [5]:
people = [[7,0], [4,4], [7,1], [5,0], [6,1], [5,2]]
people.sort( key = lambda x : (-x[0],x[1] ))
print(people)
queue = []
for p in people:
    queue.insert(p[1], p)
print(queue)

[[7, 0], [7, 1], [6, 1], [5, 0], [5, 2], [4, 4]]
[[5, 0], [7, 0], [5, 2], [6, 1], [4, 4], [7, 1]]


In [6]:
def checkPerfectNumber(num):
    """
    :type num: int
    :rtype: bool
    """
    if num < 2:
        return False
    sum = 1
    for i in range(2, int(pow(num,0.5))+1):
        if num % i ==0:
            sum += i
            if num // i != i:
                sum += num // i
            print(i, sum)
    return sum == num

checkPerfectNumber(28)

2 17
4 28


True

In [7]:
def binary_search(n):
    left, right = 1, n
    while left < right:
        mid = (left + right) >> 1
        test = mid ** 2
        if test == n:
            return True
        if test > n:
            right = mid-1
        else:
            left = mid + 1
    return False 
binary_search(15)

False

In [8]:
def judgeSquareSum(c):
    a=1
    while a * a < c:
        b = c - a * a
        if binary_search(b):
            return True
        a += 1
    return False

judgeSquareSum(6)

False

In [9]:
import numpy as np

In [10]:
a = np.arange(1,17).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
for i in range(0,5,-1):
    print(i)

In [12]:

def printInCircle(matrix, column, row, start):

    i, j = start, start
    ncol = column - start - 1
    nrow = row - start
    for flag in [1, -1]:
        for step in range(ncol):
            print(matrix[i,j], end = ' ')
            j += flag
        
        for step in range(nrow):
            print(matrix[i,j], end = ' ')
            i += flag
        i -= flag
        j -= flag
        ncol -= 1
        nrow -= 1
    print('')

printInCircle(a, 4, 4, 0)

1 2 3 4 8 12 16 15 14 13 9 5 


In [13]:
def printClockwisely(matrix):
    row, column = matrix.shape
    smaller = max(row, column) // 2
    for start in range(0, smaller):
        print("start=%d"%start)
        printInCircle(matrix, column-start, row-start, start)
        
a = np.arange(1, 13).reshape(4,3)       
print(a)
printClockwisely(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
start=0
1 2 3 6 9 12 11 10 7 4 
start=1
5 8 7 


In [14]:
def isPopOrder(push_list, pop_list):
    bPossible = False
    push_i, length = 0, len(push_list)
    stack = []
    for pop_x in pop_list:
        while push_i < length and (not stack or stack[-1] != pop_x):
            stack.append(push_list[push_i])
            push_i += 1
            print("push ",stack)

        if stack[-1] != pop_x:
            break
        stack.pop()
        print("pop", stack)

    if (not stack) and pop_list:
        bPossible = True
    return bPossible

push_list = [1,2,3,4,5]
pop_list = [4,2,1,5,3]
isPopOrder(push_list, pop_list)

push  [1]
push  [1, 2]
push  [1, 2, 3]
push  [1, 2, 3, 4]
pop [1, 2, 3]
push  [1, 2, 3, 5]


False

In [15]:
def PermutationCore(s, start):
    if start == len(s):
        print(''.join(s))
    else:
        for i in range(start, len(s)):
            s[start], s[i] = s[i], s[start]
            PermutationCore(s, start + 1)
            s[start], s[i] = s[i], s[start]
def Permutation(s):
    if not s:
        return
    s = [i for i in s]
    PermutationCore(s, 0)

Permutation('123')

123
132
213
231
321
312


In [16]:
def MoreThanHalfNum(nums):
    if not nums:
        return None
    most, count = nums[0], 0
    for i in nums:
        if i == most:
            count += 1
        else:
            count -= 1
            if count == 0:
                most, count = i, 1
        print(most, count)
    return most

nums = [2,2,3,3,2,2,1,2,4]
MoreThanHalfNum(nums)

2 1
2 2
2 1
3 1
2 1
2 2
2 1
2 2
2 1


2

In [18]:
import random

In [181]:
def Partition(nums, start, end):
    if start >= end:
        return -1
    i, j = start, end
    ti = random.randint(start, end)
    target = nums[ti]
    nums[ti], nums[start] =nums[start],nums[ti]
    while i < j:
        while i < j and nums[j] > target:
            j -= 1
        while i< j and nums[i] <= target:
            i += 1
        if i != j:
            nums[i], nums[j] = nums[j], nums[i]
    nums[start] = nums[i]
    nums[i] = target
    print(i, nums)
    return i

In [182]:
def quickSort(nums, start, end):
    sp = Partition(nums,start, end)
    if sp >= 0 :
        quickSort(nums, start, sp-1)
        quickSort(nums, sp+1, end)

In [185]:
nums = list(range(20))
random.shuffle(nums)
# nums = [6, 0, 4, 2, 1, 3, 9, 7, 5, 8]
nums = [2,2,3,3,2,2,1,2,4]
print(nums)
quickSort(nums,0,len(nums)-1)
print(nums)

[2, 2, 3, 3, 2, 2, 1, 2, 4]
0 [1, 2, 3, 3, 2, 2, 2, 2, 4]
8 [1, 2, 3, 3, 2, 2, 2, 2, 4]
7 [1, 2, 2, 3, 2, 2, 2, 3, 4]
5 [1, 2, 2, 2, 2, 2, 3, 3, 4]
4 [1, 2, 2, 2, 2, 2, 3, 3, 4]
3 [1, 2, 2, 2, 2, 2, 3, 3, 4]
2 [1, 2, 2, 2, 2, 2, 3, 3, 4]
[1, 2, 2, 2, 2, 2, 3, 3, 4]


In [186]:
def MoreThanHalfNum(nums):
    mid = len(nums) >> 1
    start, end = 0, len(nums)-1
    idx = Partition(nums, start, end)
    while idx != mid:
        if idx > mid:
            end = idx - 1
            idx = Partition(nums, start, end)
        else:
            start = idx+1
            idx = Partition(nums, start, end)
    print(nums)
    print(nums[idx])
nums = [2,2,3,3,2,2,1,2,4]
MoreThanHalfNum(nums)

8 [2, 2, 3, 3, 2, 2, 1, 2, 4]
5 [2, 2, 2, 1, 2, 2, 3, 3, 4]
4 [2, 2, 2, 1, 2, 2, 3, 3, 4]
[2, 2, 2, 1, 2, 2, 3, 3, 4]
2
