In [11]:
def quicksort(nums, left, right):
    if(left == right+1):
        return
    i = left
    j = right
    mid = nums[left]
    while(i<j):
        while(nums[j] > mid and i<j):
            j -= 1
        while(nums[i] <= mid and i<j):
            i += 1
        
        tmp = nums[j]
        nums[j] = nums[i]
        nums[i] = tmp
    nums[left] = nums[i]
    nums[i] = mid
    print(nums[left:right+1])
    quicksort(nums, left, i-1)
    quicksort(nums, i+1, right)

In [12]:
nums = [5,4,3,5,8,9,3,5,6]
quicksort(nums, 0, len(nums)-1)

[3, 4, 3, 5, 5, 5, 9, 8, 6]
[3, 3, 4, 5, 5]
[3]
[4, 5, 5]
[5, 5]
[5]
[6, 8, 9]
[6, 8]
[8]


In [46]:
import math
def generater_primes_list(n):
    is_prime = [0 if i % 2 == 0 else 1 for i in range(n+1)]
    for i in range(3, int(math.sqrt(n))+1, 2):
        if is_prime[i]:
            for m in range( i*i, n, 2*i):
                #print(m,end=' ')
                is_prime[m] = 0
            #print('')
    primes_list = [i for i in range(n+1) if is_prime[i] == 1]
    primes_list[0] = 2
    return primes_list

def PR(n):  
    primes = generater_primes_list(100)
    k = 0
    ret = []
    while(k != n):
        for p in primes:
            if n % p == 0:
                k=p
                break
        if(k != n):
            n = n // k
            ret.append(k)
    if(n>1):
        ret.append(n)
    return ret
    
primes = generater_primes_list(100000)
def PR(primes, n):  
    
    k = 1
    ret = dict()
    while(k != n):
        for p in primes:
            if n % p == 0:
                k=p
                break
        if(k != n):
            n = n / k
            if k not in ret:
                ret[k] = 1
            else:
                ret[k] += 1
                
    if k not in ret:
        ret[k] = 1
    else:
        ret[k] += 1
    return ret

PR(primes, 123)   

{3: 1, 41: 1}

In [50]:
prime_dict = dict()
for num in range(2, 100):
    pd = PR(primes, num)
    for k, v in pd.items():
        if k not in prime_dict:
            prime_dict[k] = v
        elif prime_dict[k] < v:
                prime_dict[k] = v
print(prime_dict)
res = 1
for k, v in prime_dict.items():
    res = (res * (k ** v))%987654321
print(res)

{2: 6, 3: 4, 5: 2, 7: 2, 11: 1, 13: 1, 17: 1, 19: 1, 23: 1, 29: 1, 31: 1, 37: 1, 41: 1, 43: 1, 47: 1, 53: 1, 59: 1, 61: 1, 67: 1, 71: 1, 73: 1, 79: 1, 83: 1, 89: 1, 97: 1}
445989033


In [54]:
def gcb(a,b):
    c = a%b
    while(c != 0):
        a = b
        b = c
        c = a % b
    return b

def gcb_2(a,b):
    return a if b == 0 else gcb_2(b, a%b)


In [55]:
import numpy as np

In [92]:
data = np.arange(9).reshape(3,3)
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [95]:
data =[[57,50,59,18,31,13],[67,86,93,86,4,9],[38,98,83,56,82,90],[66,50,67,11,7,69],[20,58,55,24,66,10],[43,26,65,0,64,28],[62,86,38,19,37,98]]
data = np.array(data)
print(data)

[[57 50 59 18 31 13]
 [67 86 93 86  4  9]
 [38 98 83 56 82 90]
 [66 50 67 11  7 69]
 [20 58 55 24 66 10]
 [43 26 65  0 64 28]
 [62 86 38 19 37 98]]


In [96]:
def print_order(data):
    n,m = data.shape
    flag = 1
    ret = []
    r = 0
    c = -1
    while(n!= 0 and m != 0):
        for flag in [1, -1]:
            for j in range(m):
                c += flag
                ret.append((r, c))
                
            for i in range(n-1):
                r += flag
                ret.append((r, c))
            m -= 1
            n -= 1
            
            if m == 0 or n == 0:
                break
            #print(m,n)
            #print(ret,r,c)
    return [data[i,j] for i,j in ret]
print_order(data)

[57,
 50,
 59,
 18,
 31,
 13,
 9,
 90,
 69,
 10,
 28,
 98,
 37,
 19,
 38,
 86,
 62,
 43,
 20,
 66,
 38,
 67,
 86,
 93,
 86,
 4,
 82,
 7,
 66,
 64,
 0,
 65,
 26,
 58,
 50,
 98,
 83,
 56,
 11,
 24,
 55,
 67]

In [102]:
def Add(num1, num2):
        # write code here
        carry = num1 & num2
        while(carry != 0):
            num1 = num1 ^ num2
            num2 = carry << 1
            carry = num1 & num2
        return num1 | num2
Add(1050000,15000006)

16050006

In [104]:
def jumpFloorII( number):
    # write code here
    if number == 1:
        return 1
    catalan = [0] * number
    catalan[0] = 1
    catalan[1] = 2
    for i in range(2, number):
        for j in range(i):
            catalan[i] += catalan[j] * catalan[i-1-j]
    return catalan
jumpFloorII(5)

[1, 2, 4, 12, 40]

In [108]:
a = [[0,0]] * 3
print(a)

[[0, 0], [0, 0], [0, 0]]


In [109]:
a[0][1] =1
print(a)

[[0, 1], [0, 1], [0, 1]]


In [114]:
def f(x):
    return ((x&1)<<31)>>31

In [115]:
for i in range(10):
    print(i,' ',f(i))

0   0
1   1
2   0
3   1
4   0
5   1
6   0
7   1
8   0
9   1


In [233]:
import numpy as np

In [239]:
a = [1,3,5,6,7,8,8,9,10,13,15,15,17,18,19,23,24,26,27,28,29,31,32,33,33,33,33,37,38,39,42,43,45,46,47,48]
a = np.array(a).reshape(6,6)
print(a)
array = []
for r in a:
    array.append(list(r))
print(array)

[[ 1  3  5  6  7  8]
 [ 8  9 10 13 15 15]
 [17 18 19 23 24 26]
 [27 28 29 31 32 33]
 [33 33 33 37 38 39]
 [42 43 45 46 47 48]]
[[1, 3, 5, 6, 7, 8], [8, 9, 10, 13, 15, 15], [17, 18, 19, 23, 24, 26], [27, 28, 29, 31, 32, 33], [33, 33, 33, 37, 38, 39], [42, 43, 45, 46, 47, 48]]


In [246]:
class Solution:
    # array 二维列表
    def binarySearch(self, target, array):
        left = 0
        right = len(array) - 1
        while(left <= right):
            mid = (right + left) // 2
            if array[mid] == target:
                return True
            elif array[mid] < target:
                left = mid + 1
            else:
                right = mid - 1

        return False
    def Find(self, target, array):
        # write code here
        n = len(array)
        m = len(array[0])
        for row in array:
            res = self.binarySearch(target, row)
            if res:
                return True
        return False
s = Solution()
array = [[1,2,8,9],[2,4,9,12],[4,7,10,13],[6,8,11,15]]
print(np.array(array))

res = s.Find(1, array)
print(res)
print(s.binarySearch(1,[1,2,8,9]))


[[ 1  2  8  9]
 [ 2  4  9 12]
 [ 4  7 10 13]
 [ 6  8 11 15]]
True
True


In [247]:
class MonoSum:
    def __init__(self):
        self.count = 0
        
    def merge(self, arr, start, mid, end):
        res = []
        left = start
        right = mid+1
        while (left <= mid and right <= end):
            if arr[left] <= arr[right]:
                self.count += arr[left] * (end-right+1)
                res.append(arr[left])
                left += 1
            else:
                res.append(arr[right])
                right += 1
        res += arr[left : mid+1]
        res += arr[right : end+1]
        arr[start: end+1] = res
    def mergeSort(self, arr, start, end):
        mid = (start+end) // 2
        if mid > start:
            self.mergeSort(arr, start, mid)
        if mid+1 < end:
            self.mergeSort(arr, mid+1, end)
        self.merge(arr, start, mid, end)
        
    def calcMonoSum(self, A, n):
        # write code here
        self.count = 0 
        self.mergeSort(A, 0, n-1)
        return self.count

        
arr = [1,3,5,2,4,6]
s = MonoSum()
s.mergeSort(arr, 0, len(arr)-1)
print(s.count, arr)

27 [1, 2, 3, 4, 5, 6]


In [263]:
def duplicate(arr):
    if arr == None or len(arr) == 0:
        return False
    max_len = len(arr) - 1
    for a in arr:
        if a < 0 or a > max_len:
            return False
    for i in range(len(arr)):
        while(arr[i] != i):
            cur = arr[i]
            if arr[i] != arr[cur]:
                tmp = arr[cur]
                arr[cur] = arr[i]
                arr[i] = tmp
            else:
                print("find the 1st duplicated number %d in arr[%d]"%(arr[i], i))
                return True
                break
            print(arr)
def duplicate_2(arr):
    if arr == None or len(arr) == 0:
        return False
    max_len = len(arr) - 1
    for a in arr:
        if a < 0 or a > max_len:
            return False 
    temp = [0] * (len(arr) + 1)
    for i in range(len(arr)):
        if temp[arr[i]] != 0:
            print("find the 1st duplicated number %d in arr[%d]"%(arr[i], i))
            del temp
            return True
        else:
            temp[arr[i]] += 1
        print(temp)
    del temp
    return False

def duplicate_3(arr):

    return False
        
        
#arr = [2,3,5,4,3,2,6,7]
arr = [2,3,5,4,0,1,6,7]
#duplicate(arr)
duplicate(arr)

[5, 3, 2, 4, 0, 1, 6, 7]
[1, 3, 2, 4, 0, 5, 6, 7]
[3, 1, 2, 4, 0, 5, 6, 7]
[4, 1, 2, 3, 0, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7]


In [264]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [268]:
def Find(A, row, col, num):
    found = False
    if row * col != 0:
        n = 0; m = col - 1
        while(n < row and col >= 0):
            if num == A[n,m]:
                found = True
                break
            elif num < A[n, m]:
                m -= 1
            else:
                n += 1
    return found
Find(a, a.shape[0], a.shape[1], 5)

True