In [2]:
from copy import deepcopy

In [14]:
def InversePairsCore(data, copy, start, end):
    if start == end:
        #copy[start] = data[start]
        return 0
    length = (end - start) // 2
    left = InversePairsCore(copy, data, start, start + length)
    right = InversePairsCore(copy, data, start + length + 1, end)
    i, j = start+length, end
    indexCopy = end
    count = 0
    print("----------------------------------")
    while i >= start and j >= start+length+1:
        if data[i] > data[j]:
            copy[indexCopy] = data[i]
            count += j - (start+length)
            i -= 1
        else:
            copy[indexCopy] = data[j]
            j -= 1
        print(copy[start:end+1])
        indexCopy -= 1
    while i >= start:
        copy[indexCopy] = data[i]
        i -= 1
        indexCopy -= 1
        print(print(copy[start:end+1]))
    while j >= start+length+1:
        copy[indexCopy] = data[j]
        j -= 1
        indexCopy -= 1
        print(copy[start:end+1])
    return left + right + count

In [17]:
def InversePairs(data):
    if not data or len(data) == 0:
        return
    length = len(data)
    copy = [None] * length #deepcopy(data)
    count = InversePairsCore(data, copy, 0, length-1)
    del copy
    return count

In [18]:
arr = [3,9,1,7,5,2,6,4]
InversePairs(arr)

----------------------------------
[None, 9]
[3, 9]
None
----------------------------------
[None, 7]
[1, 7]
None
----------------------------------
[3, 9, 1, 9]
[3, 9, 7, 9]
[3, 3, 7, 9]
[1, 3, 7, 9]
----------------------------------
[None, 5]
[2, 5]
----------------------------------
[None, 6]
[4, 6]
----------------------------------
[5, 2, 6, 6]
[5, 2, 5, 6]
[5, 4, 5, 6]
[2, 4, 5, 6]
None
----------------------------------
[3, 9, 1, 7, 2, 5, 4, 9]
[3, 9, 1, 7, 2, 5, 7, 9]
[3, 9, 1, 7, 2, 6, 7, 9]
[3, 9, 1, 7, 5, 6, 7, 9]
[3, 9, 1, 4, 5, 6, 7, 9]
[3, 9, 3, 4, 5, 6, 7, 9]
[3, 2, 3, 4, 5, 6, 7, 9]
[1, 2, 3, 4, 5, 6, 7, 9]
None


15

In [2]:
import numpy as np

In [16]:
a = np.arange(36).reshape(6,6)
#np.random.shuffle(a)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [27]:
def get_S(matrix):
    if matrix is None:
        return None
    if len(matrix[0]) == 0:
        return None
    n, m = len(matrix), len(matrix[0])
    s = [[0] * m for _ in range(n)]
    s[0][0] = matrix[0][0]
    for j in range(1,m):
        s[0][j] = s[0][j-1] + matrix[0][j]
    for i in range(1, n):
        row_sum = 0
        for j in range(0, m):
            row_sum += matrix[i][j]
            s[i][j] = s[i-1][j] + row_sum
    return s

s = get_S(a)
print(np.array(s))

def get_sum(s, r1, c1, r2, c2):
    if r1 < 0 or r2 < 0 or  r1 > r2 or c1 > c2:
        return 0
    ret = s[r2][c2]
    flag = False
    if r1 >= 1:
        ret -= s[r1-1][c2]
        flag = True
    if c1 >= 1:
        ret -= s[r2][c1-1]
        if flag:
            ret += s[r1-1][c1-1]
    return ret

get_sum(s, 3,3,3,3)

[[  0   1   3   6  10  15]
 [  6  14  24  36  50  66]
 [ 18  39  63  90 120 153]
 [ 36  76 120 168 220 276]
 [ 60 125 195 270 350 435]
 [ 90 186 288 396 510 630]]
2 3 90
3 2 120


21

In [1]:
def getFirstK(data, k, start, end):
    if start >= end:
        return -1
    mid = (start + end) >> 1
    
arr = [1,2,3,3,3,3,4,5]


SyntaxError: invalid syntax (<ipython-input-1-3bf62ab07e60>, line 2)