题目1:

    所有的同学都站在坐标系上的整数点,由原点看每个点,有的点被视线挡住了,求(长度为N时)原点能看到多少点,如下图所示:比如N = 1时 输出3; N=2时 输出5; N=3时 输出9; N = 4时,输出13

思路：

    1. 对于坐标（x,y）可约分，可被遮挡。反之，能被看见
    2. 因为是正方形，沿着对角线对称，对角线只有(1,1)可以被看见。总数 = 下三角 * 2 + 1

In [12]:
#站在原点能看几个其他的点
def checkReduce(a, b):
    #检查坐标是否可以约分
    minone = min(a,b)
    maxone = max(a,b)
    if minone >1 and maxone % minone == 0:
        return True
    for i in range(2, int(pow(minone,0.5)+1)):
        if a % i == 0 and b % i == 0:
            return True
    return False

def FindStar(N):
    count = 1
    for i in range(1, N+1):
        for j in range(i+1, N+1):
            if checkReduce(i,j) == False:
                count += 1
    return count * 2 + 1

for i in [1,2,3,4]:
    print(FindStar(i))

3
5
9
13


题目2 ：
    
    一个圆分成n个扇形，用m种颜色上色，要求相邻两个颜色不同。求有多少种不同的方法。
分析：

    特殊：
    1. n = 1 有 m 种填法
    2. n = 2 有 m * (m - 1) 种
    3. m < 2 and n > 2 无解
    
    一般：
    对于S(n,m) 来说，第一个扇面有m种选择，之后 n-1 个扇面各有 m - 1 中选择。由于最后一个和第一个相邻，所以存在重复。
    重复的个数刚好是S(n-1, m). 于是有递推公式 
$$ S(n - m) = m * (m-1)^{(n-1)} - S(n-1, m) $$

In [27]:
def filling(n,m, cache=dict()):
    if n < 1 or m < 1:
        return 0
    elif n == 1:
        return m
    elif n == 2:
        return m * (m - 1)
    if m < 2:
        return 0
    key = n *m + m
    c = cache.get(key, None)
    if c is not None:
        ret = c
    else:
        ret = m * pow(m-1, n-1) - filling(n-1,m, cache)
        cache[key] = ret
    return ret

filling(4,4)

84

题目3

    对于一个长度为N的整形数组A,数组里所有的数都是正数,用三个下标m1,m2,m3
    (满足条件 0<m1<m1+1<m2<m2+1<m3<N-1)
    将数组A分成(0,m1-1),(m1+1,m2-1),(m2+1,m3-1),(m3+1,N-1)四个切片;
    如果这四个切片中的正数求和相等,则为"四等分".
    编写一个函数,求一个给定的整形数组是否可以四等分,可以返回true,不可以返回false.
    限制条件: N<= 1000000;
    要求:空间复杂度最多为O(n);时间复杂度为O(n);
    例子:
    [2,5,1,1,1,1,4,1,7,3,7] true
    [10,2,11,13,1,1,1,1] false
    
分析： 
    1. 设置首尾两个指针 low, high , 切片的和为sum1 ~ sum4, 如果有解，必定在high > low 的情况下，存在某两个断点使得sum1 == sum4 = s
    2. 如果条件1成立，只需要从上述断点之间再调出一个断点使得s2 ==s3
    3. 最后比较 s1 == s2

In [29]:
def resolve(A):
    if not A or len(A) < 7:
        return False
    low, high = 0, len(A)-1
    s1, s4 = A[low], A[high]
    while low < high:
        if s1 == s4 :
            break
        elif s1 < s4:
            low += 1
            s1 += A[low]
        else:
            high -= 1
            s4 += A[high]
    if s1 == s4:
        flag1, flag3 = low+1, high-1
        low, high = low+2, high-2
        if low < high:
            s2, s3 = A[low], A[high]
            while low < high:
                if s2 == s3:
                    break
                elif s2 < s3:
                    low += 1
                    s2 += A[low]
                else:
                    high -= 1
                    s3 -= A[high]
            if s2 == s3 and s2 == s4:
                return True
    return False
A = [10,2,11,13,1,1,1,1]
resolve(A)

False

题目4
    
    给定一个正整数数组，每个元素大小表示从该元素出发最多可移动几个节点。假设总是从第一个元素开始移动。
    问如何移动可以以最少的步数移动到最后。 
    Input: [2,3,1,1,4] 
    Output: 2
    
分析：
    
    当前为2时， 最大移动步数为2， 可以移动到3,1。
    1. 若移动到3时，最大移动步数为1+3 = 4
    2. 若一到到1时，最大移动步数为2+1 = 3
    3. 移动步数从下一个位置开始，所以上述样例中，只需要4步移动就可以到达最后一个元素，结束

In [34]:
def jump(nums):
    n, start, end, step = len(nums), 0, 0, 0
    while end < n-1:
        step += 1
        maxend = end + 1
        print(start, end+1)
        for i in range(start, end+1):
            if i + nums[i] >= n-1:
                return step
            maxend = max(maxend, i+nums[i])
        start, end = end, maxend
    return step
A = [2,3,1,1,4]
jump(A)

0 1
0 3


2

题目5

    对于一个由一位十进制整数构成的二叉树，如果深度不超过4，可以用一个三位十进制整数构成的数组表示，具体规则如下：
    1. 百位数表示树的层次L，1<=L<=4；十位数表示在该层次中的位置P，1<=P<=8；个位数表示数值V。
    2. 数组里，L一定是单增的，也就是说后一个数的L大于等于前一个数的L。
    3. 对于同一个L，P也是单增的，就是说在L不变的情况下，后一个数的P大于等于前一个数的P。
    
    例如：
    [113, 215, 221]对应的树是：
       3
      /  \
     5    1
     
    现在要求这个树所有到叶子节点的路径和，对于[113, 215, 221] 这棵树，有两个路径3-5和 3-1，路径和是(3+5) + (3 + 1) = 12

In [3]:
def TreeRoute(arr):
    tree = [None] * 16
    for a in arr:
        level = a // 100
        l_pos = (a//10) % 10
        val = a %10
        pos = 2 ** (level-1) + l_pos - 1
        tree[pos] = val
    print(tree)
    s = 0
    for cur in range(16-8, 16):
        while cur !=0 and tree[cur] is not None:
            s += tree[cur]
            cur = cur // 2
    return s
arr=[113, 215, 221, 316, 328, 342, 427, 439, 474]
TreeRoute(arr)

[None, 3, 5, 1, 6, 8, None, 2, None, 7, 9, None, None, None, 4, None]


56

题目6 ： 01 背包的模板

    有N件物品和一个容量为V的背包。第i件物品的费用是c[i]，价值是w[i]。求解将哪些物品装入背包可使这些物品的费用总和不超过背包容量，且价值总和最大。 f[i][v]表示前i件物品恰放入一个容量为v的背包可以获得的最大价值。则其状态转移方程便是：f[i][v]=max{f[i-1][v],f[i-1][v-c[i]]+w[i]}。将前i件物品放入容量为v的背包中”这个子问题，若只考虑第i件物品的策略（放或不放），那么就可以转化为一个只牵扯前i-1件物品的问题。如果不放第i件物品，那么问题就转化为“前i-1件物品放入容量为v的背包中”；如果放第i件物品，那么问题就转化为“前i-1件物品放入剩下的容量为v-c[i]的背包中”，此时能获得的最大价值就是f [i-1][v-c[i]]再加上通过放入第i件物品获得的价值w[i]。

In [1]:
import numpy as np

In [11]:
def backtrack(weights, values, maxWeight):
    N = len(weights)
    bag = [[0] * (maxWeight+1) for _ in range(N+1)]

    for i in range(1, N+1):
        for j in range(1,maxWeight+1):
            if weights[i-1] <= j:
                bag[i][j] = max(bag[i-1][j], bag[i-1][j-weights[i-1]] + values[i-1])
            else:
                bag[i][j] = bag[i-1][j]
    b = np.array(bag)
    print(b)
    return bag[N][maxWeight]
weights = [2,2,6,5,4]
values = [6,3,5,4,6]
backtrack(weights, values, 10)

[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  6  6  6  6  6  6  6  6]
 [ 0  0  6  6  9  9  9  9  9  9  9]
 [ 0  0  6  6  9  9  9  9 11 11 14]
 [ 0  0  6  6  9  9  9 10 11 13 14]
 [ 0  0  6  6  9  9 12 12 15 15 15]]


15

题目7：

给出N个数，每次从中抽出一个数(第一和最后一个不能抽)，该次的得分即为抽出的数与相邻两个数的乘积。一直这样将每次的得分累加直到只剩下首尾两个数为止，问最小得分。